/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    GameBoard: typeof import('./src/components/game/board/GameBoard.vue')['default']
    GameBoardItem: typeof import('./src/components/game/board/GameBoardItem.vue')['default']
    GameBoardMark: typeof import('./src/components/game/board/GameBoardMark.vue')['default']
    GameEnd: typeof import('./src/components/game/GameEnd.vue')['default']
    GameResult: typeof import('./src/components/game/GameResult.vue')['default']
    GameToolbar: typeof import('./src/components/game/GameToolbar.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
